######################################################################
##
## Filename: frame_tb.udo
## Created on: Mon Feb 01 11:15:07 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
